### ISSUE TITLE
When logging in with an agency account but able to type the admin URL and access the Admin section

### ISSUE THREAD

**Issue by gnfdedsec** [masternonnolnw/template-nextjs-frontend#2]
![Image](https://github.com/masternonnolnw/template-nextjs-frontend/assets/61729539/cea9a40e-f5fc-409c-a4b2-1469853a5660)
![Image](https://github.com/masternonnolnw/template-nextjs-frontend/assets/61729539/612e1556-5659-4ee3-8310-dd1dca7f38c9)

**Comment by masternonnolnw** [comment]
อันนี้ถึงเข้าหน้านี้ได้ก็ไม่สามารถทำอะไรได้อยู่ดีครับผม เพราะไม่มีสิทธิ์ fetch ข้อมูลครับ 
การพิมพ์ URL เข้ามาแบบนี้ user จะไม่เจออยู่แล้วครับ
แต่ถ้ามีคนพิมพ์มาจริงๆก็ทำอะไรไม่ได้ครับ
